2025-06-18 15:30:15,469 - INFO - --------------------------------------------
2025-06-18 15:30:15,469 - INFO - Entered Main Function...
2025-06-18 15:30:16,109 - INFO - Records found within the date range. Running reconciliation...
2025-06-18 15:30:16,109 - INFO - Entering Reconciliation for AEPS Service
2025-06-18 15:30:16,115 - INFO - AEPS service: Column 'SERIALNUMBER' renamed to 'REFID'
2025-06-18 15:30:16,115 - INFO - Fetching data from HUB for AEPS
2025-06-18 15:30:16,116 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:30:17,857 - INFO - Fetching Data from EBO Wallet Transaction
2025-06-18 15:30:17,857 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:30:19,054 - INFO - Filteration Starts for AEPS service
2025-06-18 15:30:19,111 - INFO - Filteration Ends
2025-06-18 15:30:19,112 - INFO - Reconciliation Ends
2025-06-18 15:30:19,118 - INFO - Result sent as API
2025-06-18 15:30:19,118 - INFO - ----------------------------------
2025-06-18 15:34:12,809 - INFO - --------------------------------------------
2025-06-18 15:34:12,827 - INFO - Entered Main Function...
2025-06-18 15:34:13,861 - INFO - Records found within the date range. Running reconciliation...
2025-06-18 15:34:13,863 - INFO - Entering Reconciliation for AEPS Service
2025-06-18 15:34:13,867 - INFO - AEPS service: Column 'SERIALNUMBER' renamed to 'REFID'
2025-06-18 15:34:13,868 - INFO - Fetching data from HUB for AEPS
2025-06-18 15:34:13,883 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:34:13,939 - ERROR - Error during SQL execution: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: 
        SELECT 
            mt2.TransactionRefNum AS IHUB_REFERENCE,
            pat.BankRrn AS VENDOR_REFERENCE,
            mt2.TenantDetailId as TENANT_ID,
            u.UserName as IHUB_USERNAME,
            mt2.TransactionStatus AS IHUB_MASTER_STATUS,
            pat.CreationTs AS SERVICE_DATE,
            pat.TransStatus AS service_status,
            CASE 
                WHEN a.IHubReferenceId IS NOT NULL THEN 'Yes'
                ELSE 'No'
            END AS IHUB_LEDGER_STATUS
        FROM ihubcore.MasterTransaction mt2 
        LEFT JOIN ihubcore.MasterSubTransaction mst
            ON mst.MasterTransactionId = mt2.Id
        LEFT JOIN ihubcore.PsAepsTransaction pat 
            ON pat.MasterSubTransactionId = mst.Id
        LEFT JOIN tenantinetcsc.EboDetail ed
            ON mt2.EboDetailId = ed.Id
        LEFT JOIN tenantinetcsc.`User` u
            ON u.id = ed.UserId
        LEFT JOIN (
            SELECT DISTINCT iwt.IHubReferenceId AS IHubReferenceId
            FROM ihubcore.IHubWalletTransaction iwt
            WHERE DATE(iwt.CreationTs) BETWEEN %(start_date)s AND CURRENT_DATE()
        ) a 
            ON a.IHubReferenceId = mt2.TransactionRefNum
        WHERE pat.TransMode = %(transaction_type)s
        AND DATE(pat.CreationTs) BETWEEN %(start_date)s AND %(end_date)s
    ]
[parameters: {'start_date': datetime.date(2025, 5, 1), 'transaction_type': '2', 'end_date': datetime.date(2025, 5, 31)}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-18 15:34:14,943 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:34:25,733 - INFO - Fetching Data from EBO Wallet Transaction
2025-06-18 15:34:25,734 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:34:45,368 - INFO - Filteration Starts for AEPS service
2025-06-18 15:34:45,460 - INFO - Filteration Ends
2025-06-18 15:34:45,462 - INFO - Reconciliation Ends
2025-06-18 15:34:45,487 - INFO - Result sent as API
2025-06-18 15:34:45,487 - INFO - ----------------------------------
2025-06-18 15:40:49,929 - INFO - --------------------------------------------
2025-06-18 15:40:49,931 - INFO - Entered Main Function...
2025-06-18 15:40:50,764 - INFO - Records found within the date range. Running reconciliation...
2025-06-18 15:40:50,765 - INFO - Entering Reconciliation for AEPS Service
2025-06-18 15:40:50,768 - INFO - AEPS service: Column 'SERIALNUMBER' renamed to 'REFID'
2025-06-18 15:40:50,768 - INFO - Fetching data from HUB for AEPS
2025-06-18 15:40:50,768 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:40:50,770 - ERROR - Error during SQL execution: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: 
        SELECT 
            mt2.TransactionRefNum AS IHUB_REFERENCE,
            pat.BankRrn AS VENDOR_REFERENCE,
            mt2.TenantDetailId as TENANT_ID,
            u.UserName as IHUB_USERNAME,
            mt2.TransactionStatus AS IHUB_MASTER_STATUS,
            pat.CreationTs AS SERVICE_DATE,
            pat.TransStatus AS service_status,
            CASE 
                WHEN a.IHubReferenceId IS NOT NULL THEN 'Yes'
                ELSE 'No'
            END AS IHUB_LEDGER_STATUS
        FROM ihubcore.MasterTransaction mt2 
        LEFT JOIN ihubcore.MasterSubTransaction mst
            ON mst.MasterTransactionId = mt2.Id
        LEFT JOIN ihubcore.PsAepsTransaction pat 
            ON pat.MasterSubTransactionId = mst.Id
        LEFT JOIN tenantinetcsc.EboDetail ed
            ON mt2.EboDetailId = ed.Id
        LEFT JOIN tenantinetcsc.`User` u
            ON u.id = ed.UserId
        LEFT JOIN (
            SELECT DISTINCT iwt.IHubReferenceId AS IHubReferenceId
            FROM ihubcore.IHubWalletTransaction iwt
            WHERE DATE(iwt.CreationTs) BETWEEN %(start_date)s AND CURRENT_DATE()
        ) a 
            ON a.IHubReferenceId = mt2.TransactionRefNum
        WHERE pat.TransMode = %(transaction_type)s
        AND DATE(pat.CreationTs) BETWEEN %(start_date)s AND %(end_date)s
    ]
[parameters: {'start_date': datetime.date(2025, 5, 1), 'transaction_type': '2', 'end_date': datetime.date(2025, 5, 31)}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-18 15:40:51,771 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:41:01,757 - INFO - Fetching Data from EBO Wallet Transaction
2025-06-18 15:41:01,757 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 15:41:20,635 - INFO - Filteration Starts for AEPS service
2025-06-18 15:41:20,692 - INFO - Filteration Ends
2025-06-18 15:41:20,693 - INFO - Reconciliation Ends
2025-06-18 15:41:20,715 - INFO - Result sent as API
2025-06-18 15:41:20,716 - INFO - ----------------------------------
2025-06-18 17:49:16,302 - INFO - --------------------------------------------
2025-06-18 17:49:16,312 - INFO - Entered Main Function...
2025-06-18 17:49:18,069 - INFO - Records found within the date range. Running reconciliation...
2025-06-18 17:49:18,071 - INFO - Entering Reconciliation for AEPS Service
2025-06-18 17:49:18,074 - INFO - AEPS service: Column 'SERIALNUMBER' renamed to 'REFID'
2025-06-18 17:49:18,074 - INFO - Fetching data from HUB for AEPS
2025-06-18 17:49:18,084 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 17:49:29,320 - INFO - Fetching Data from EBO Wallet Transaction
2025-06-18 17:49:29,320 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 17:49:48,800 - INFO - Filteration Starts for AEPS service
2025-06-18 17:49:48,837 - ERROR - Error in main(): You are trying to merge on int64 and object columns for key 'VENDOR_REFERENCE'. If you wish to proceed you should use pd.concat
2025-06-18 17:49:48,839 - INFO - Result sent as API
2025-06-18 17:49:48,839 - INFO - ----------------------------------
2025-06-18 17:55:51,820 - INFO - --------------------------------------------
2025-06-18 17:55:51,820 - INFO - Entered Main Function...
2025-06-18 17:55:52,817 - INFO - Records found within the date range. Running reconciliation...
2025-06-18 17:55:52,817 - INFO - Entering Reconciliation for AEPS Service
2025-06-18 17:55:52,821 - INFO - AEPS service: Column 'SERIALNUMBER' renamed to 'REFID'
2025-06-18 17:55:52,821 - INFO - Fetching data from HUB for AEPS
2025-06-18 17:55:52,822 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 17:56:04,046 - INFO - Fetching Data from EBO Wallet Transaction
2025-06-18 17:56:04,046 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 17:56:25,269 - INFO - Filteration Starts for AEPS service
2025-06-18 17:56:25,291 - ERROR - Error in main(): You are trying to merge on int64 and object columns for key 'VENDOR_REFERENCE'. If you wish to proceed you should use pd.concat
2025-06-18 17:56:25,292 - INFO - Result sent as API
2025-06-18 17:56:25,292 - INFO - ----------------------------------
2025-06-18 17:59:34,024 - INFO - --------------------------------------------
2025-06-18 17:59:34,025 - INFO - Entered Main Function...
2025-06-18 17:59:34,912 - INFO - Records found within the date range. Running reconciliation...
2025-06-18 17:59:34,912 - INFO - Entering Reconciliation for AEPS Service
2025-06-18 17:59:34,916 - INFO - AEPS service: Column 'SERIALNUMBER' renamed to 'REFID'
2025-06-18 17:59:34,916 - INFO - Fetching data from HUB for AEPS
2025-06-18 17:59:34,917 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 17:59:45,707 - INFO - Fetching Data from EBO Wallet Transaction
2025-06-18 17:59:45,707 - INFO - Entered helper function to execute SQL with retry logic
2025-06-18 18:00:05,216 - INFO - Filteration Starts for AEPS service
2025-06-18 18:00:05,288 - INFO - Filteration Ends
2025-06-18 18:00:05,289 - INFO - Reconciliation Ends
2025-06-18 18:00:05,311 - INFO - Result sent as API
2025-06-18 18:00:05,312 - INFO - ----------------------------------
